# Generated by Django 3.1.6 on 2021-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uplod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('action', models.CharField(blank=True, choices=[('NO_FILTER', 'NO_FILTER'), ('COLORIZE', 'COLORIZE'), ('GRAYSCALE', 'GRAYSCALE'), ('BLURRED', 'BLURRED'), ('BINARY', 'BINARY'), ('INVERT', 'BINARY INVERS')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
