# Generated by Django 3.1.6 on 2021-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplod',
            name='image_binary',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
