# Generated by Django 3.1.6 on 2021-05-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_uplod_image_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uplod',
            name='image_binary',
        ),
    ]
