# Generated by Django 3.1.6 on 2021-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_remove_uplod_image_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplod',
            name='action',
            field=models.CharField(blank=True, choices=[('NO_FILTER', 'NO_FILTER'), ('COLORIZE', 'COLORIZE'), ('GRAYSCALE', 'GRAYSCALE'), ('BLURRED', 'BLURRED'), ('BINARY', 'BINARY'), ('INVERT', 'BINARY INVERS'), ('EADGES', 'EADGES DETECTION')], max_length=50),
        ),
    ]
