# Generated by Django 3.1.6 on 2021-05-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20210531_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplod',
            name='action',
            field=models.CharField(blank=True, choices=[('NO_FILTER', 'NO_FILTER'), ('HISTOGRAM', 'HISTOGRAM'), ('COLORIZE', 'COLORIZE'), ('GRAYSCALE', 'GRAYSCALE'), ('BLURRED', 'BLURRED'), ('BINARY', 'BINARY'), ('INVERT', 'BINARY INVERS'), ('EADGES', 'EADGES DETECTION'), ('NOICE', 'REDUCE NOICE')], max_length=50),
        ),
    ]
