# Generated by Django 3.1.6 on 2021-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='petaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=30)),
                ('p_gender', models.CharField(choices=[('Male', 'male'), ('Femal', 'Femal')], max_length=30)),
                ('p_age', models.IntegerField()),
                ('p_report', models.CharField(max_length=80)),
                ('p_coved', models.CharField(choices=[('Nagative', 'Nagative'), ('Positive', 'Positive')], max_length=50)),
                ('P_per', models.IntegerField()),
                ('P_x_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
