# Generated by Django 3.1.6 on 2021-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_data', '0003_auto_20210522_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='petaint',
            name='Dr_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petaint',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='petaint',
            name='bed_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petaint',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petaint',
            name='ward_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
