# Generated by Django 3.1.6 on 2021-06-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_data', '0005_auto_20210626_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petaint',
            name='Ventilator',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
