# Generated by Django 3.1.6 on 2021-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_data', '0006_auto_20210626_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='petaint',
            name='discharge',
            field=models.BooleanField(default=False),
        ),
    ]
