# Generated by Django 3.1.6 on 2021-07-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x_data', '0007_petaint_discharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petaint',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='petaint',
            name='updated',
        ),
    ]
